/* GENERATED by tools/spritegen.py — edit the files in assets/sprites/ instead */
#ifndef TAMA_SPRITES_H
#define TAMA_SPRITES_H

#include <stdint.h>

typedef struct {
    uint8_t  w, h, bpp, frames;
    uint8_t  n_pal;
    const uint32_t *palette;   /* [0] unused (transparent); rest 0xRRGGBB */
    const uint8_t  *data;      /* bit-packed, rows byte-aligned, frames consecutive */
} tama_sprite_t;

enum {
    SPR_ICON_CLOCK,
    SPR_ICON_FEED,
    SPR_ICON_GAME,
    SPR_ICON_LIGHT,
    SPR_ICON_MEDS,
    SPR_ICON_SCOLD,
    SPR_ICON_STAT,
    SPR_ICON_WC,
    SPR_PET_ADULT_AVG,
    SPR_PET_ADULT_CHEER,
    SPR_PET_ADULT_FERAL,
    SPR_PET_ADULT_GRUMP,
    SPR_PET_ADULT_HERO,
    SPR_PET_BABY,
    SPR_PET_CHILD,
    SPR_PET_EGG,
    SPR_PET_SECRET,
    SPR_PET_TEEN_BAD,
    SPR_PET_TEEN_GOOD,
    SPR_PROP_ATTENTION,
    SPR_PROP_HEART_EMPTY,
    SPR_PROP_HEART_FULL,
    SPR_PROP_MEAL,
    SPR_PROP_MOON,
    SPR_PROP_POOP,
    SPR_PROP_SKULL,
    SPR_PROP_SNACK,
    SPR_PROP_SUN,
    SPR_PROP_TOMBSTONE,
    SPR_PROP_ZZZ,
    SPR_COUNT
};

extern const tama_sprite_t TAMA_SPRITES[SPR_COUNT];

#endif /* TAMA_SPRITES_H */
