#!/usr/bin/env python3
"""spritegen — ASCII pixel-art -> C arrays for WatchaGotchi.

Input: assets/sprites/<name>.txt
    size <w> <h>
    palette <char> transparent      # first palette entry MUST be transparent
    palette <char> <rrggbb>
    frame
    <h rows of w chars>
    frame
    ...

Output: main/tama_sprites.c / main/tama_sprites.h (committed), with each
sprite packed at 1/2/4 bpp (smallest that fits the palette) plus a lookup
table indexed by SPR_<NAME>.

Stdlib only; deterministic output (stable ordering) so diffs stay readable.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
ASSETS = os.path.join(ROOT, "assets", "sprites")
OUT_C = os.path.join(ROOT, "main", "tama_sprites.c")
OUT_H = os.path.join(ROOT, "main", "tama_sprites.h")


def parse(path):
    name = os.path.splitext(os.path.basename(path))[0]
    if not re.fullmatch(r"[a-z0-9_]+", name):
        sys.exit(f"{path}: file name must be [a-z0-9_]+")
    w = h = None
    pal_chars, pal_colors = [], []
    frames, cur = [], None
    with open(path) as f:
        for ln, raw in enumerate(f, 1):
            line = raw.rstrip("\n")
            if not line.strip() or line.lstrip().startswith("//"):
                continue
            tok = line.split()
            if tok[0] == "size":
                w, h = int(tok[1]), int(tok[2])
            elif tok[0] == "palette":
                ch, col = tok[1], tok[2]
                if len(ch) != 1:
                    sys.exit(f"{path}:{ln}: palette char must be 1 char")
                pal_chars.append(ch)
                if col == "transparent":
                    if len(pal_chars) != 1:
                        sys.exit(f"{path}:{ln}: transparent must be the FIRST palette entry")
                    pal_colors.append(None)
                else:
                    pal_colors.append(int(col, 16))
            elif tok[0] == "frame":
                cur = []
                frames.append(cur)
            else:
                if cur is None:
                    sys.exit(f"{path}:{ln}: pixel row before any 'frame'")
                if w is None or len(line) != w:
                    sys.exit(f"{path}:{ln}: row is {len(line)} chars, want {w}")
                cur.append(line)
    if w is None or not frames:
        sys.exit(f"{path}: needs size + at least one frame")
    if pal_colors[0] is not None:
        sys.exit(f"{path}: first palette entry must be transparent")
    for i, fr in enumerate(frames):
        if len(fr) != h:
            sys.exit(f"{path}: frame {i} has {len(fr)} rows, want {h}")
        for row in fr:
            for c in row:
                if c not in pal_chars:
                    sys.exit(f"{path}: frame {i} uses char {c!r} not in palette")
    n = len(pal_chars)
    bpp = 1 if n <= 2 else 2 if n <= 4 else 4
    if n > 16:
        sys.exit(f"{path}: max 16 palette entries")
    return dict(name=name, w=w, h=h, bpp=bpp,
                pal_chars=pal_chars, pal_colors=pal_colors, frames=frames)


def pack(s):
    """bit-pack all frames, row-major, rows padded to a byte boundary."""
    idx = {c: i for i, c in enumerate(s["pal_chars"])}
    ppb = 8 // s["bpp"]                      # pixels per byte
    out = []
    for fr in s["frames"]:
        for row in fr:
            byte, nin = 0, 0
            for c in row:
                byte = (byte << s["bpp"]) | idx[c]
                nin += 1
                if nin == ppb:
                    out.append(byte)
                    byte, nin = 0, 0
            if nin:
                byte <<= s["bpp"] * (ppb - nin)
                out.append(byte)
    return out


def carray(vals, per_line=16):
    lines = []
    for i in range(0, len(vals), per_line):
        lines.append("    " + ", ".join(f"0x{v:02x}" for v in vals[i:i + per_line]) + ",")
    return "\n".join(lines)


def main():
    files = sorted(
        os.path.join(ASSETS, f) for f in os.listdir(ASSETS) if f.endswith(".txt")
    ) if os.path.isdir(ASSETS) else []
    if not files:
        sys.exit(f"no sprite sources in {ASSETS}")
    sprites = [parse(p) for p in files]

    h = ["/* GENERATED by tools/spritegen.py — edit the files in assets/sprites/ instead */",
         "#ifndef TAMA_SPRITES_H", "#define TAMA_SPRITES_H", "",
         "#include <stdint.h>", "",
         "typedef struct {",
         "    uint8_t  w, h, bpp, frames;",
         "    uint8_t  n_pal;",
         "    const uint32_t *palette;   /* [0] unused (transparent); rest 0xRRGGBB */",
         "    const uint8_t  *data;      /* bit-packed, rows byte-aligned, frames consecutive */",
         "} tama_sprite_t;", "",
         "enum {"]
    for s in sprites:
        h.append(f"    SPR_{s['name'].upper()},")
    h += ["    SPR_COUNT", "};", "",
          "extern const tama_sprite_t TAMA_SPRITES[SPR_COUNT];", "",
          "#endif /* TAMA_SPRITES_H */", ""]

    c = ["/* GENERATED by tools/spritegen.py — edit the files in assets/sprites/ instead */",
         '#include "tama_sprites.h"', ""]
    for s in sprites:
        pal = ["0x000000" if col is None else f"0x{col:06x}" for col in s["pal_colors"]]
        c.append(f"static const uint32_t pal_{s['name']}[] = {{ {', '.join(pal)} }};")
        c.append(f"static const uint8_t dat_{s['name']}[] = {{")
        c.append(carray(pack(s)))
        c.append("};\n")
    c.append("const tama_sprite_t TAMA_SPRITES[SPR_COUNT] = {")
    for s in sprites:
        c.append(f"    [SPR_{s['name'].upper()}] = {{ {s['w']}, {s['h']}, {s['bpp']}, "
                 f"{len(s['frames'])}, {len(s['pal_chars'])}, pal_{s['name']}, dat_{s['name']} }},")
    c += ["};", ""]

    with open(OUT_H, "w") as f:
        f.write("\n".join(h))
    with open(OUT_C, "w") as f:
        f.write("\n".join(c))
    total = sum(len(pack(s)) for s in sprites)
    print(f"spritegen: {len(sprites)} sprites, {total} bytes packed -> main/tama_sprites.[ch]")
    for s in sprites:
        print(f"  {s['name']:24s} {s['w']}x{s['h']}  {s['bpp']}bpp  {len(s['frames'])} frames")


if __name__ == "__main__":
    main()
